name: Functional Tests

on: 
  push:
    branches:
      - workflowsR

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Up the Docker
      run: php artisan migrate --package=cmgmyr/messenger && php artisan serve --host=0.0.0.0 --port=8181 && pip3 install selenium && pip3 install pyvirtualdisplay && python3 test.py


      # docker exec arquigrafialaravelrobson_db_1 bash -c "mysql insert_user_docker.sql"