name: Docker Image and Tests CI

on: 
  push:
    branches:
      - workflows

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Up the Docker
      run: docker-compose up -d && python3 -c "print('oi')"